// <auto-generated />
namespace Product_34.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class product34Init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(product34Init));
        
        string IMigrationMetadata.Id
        {
            get { return "202411261435371_product34Init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
